version: '3.4'

services:
  new-weather-archiver:
    image: new-weather-archiver
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - ${PORT_MAP}:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: ['npm', 'run', 'dev']
  db:
    image: postgis/postgis:13-master
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT_MAP}:5432
volumes:
  db:
